### ISSUE TITLE
LCD code?

### ISSUE THREAD

**Issue by mieg** [Jakeler/Model-N-Thermostat#1]
Hi Jake,
I have done what you have done, and connected (for now) an esp-link to the UART, so i can open and close the valve with your f- and b-commands by telnet. I am now extending your code so i can control it from esphome. It would be nice to also show something on the LCD, and i saw you already did that in your video. Would you be willing to share your LCD-code also? Of course I will share all the combined (custom esphome and stm8) code on github.

**Comment by Jakeler** [comment]
Hi, I did not make a video about this project to be honest ;)
Now i searched quickly, guess you are writing about these:
https://www.youtube.com/watch?v=VsatF105nFc
https://www.youtube.com/watch?v=ZgehIGf_Mik
He mentioned my/this firmware in the videos, but he progressed much more on the LCD and seems to have got it completely working. Really interesting. Also he talks about calibration and time measurement for the motor control, so he probably got also a bit further there.
I will write him an email now and post here if there is something new. 
Would be nice to finally finish this project.

**Comment by mieg** [comment]
Hi Jake,

I'm sorry, i thought you were one and the same :-) Yes we should ask him. I am trying to write the code to do calibration and then use timing to set the thermostat to a percentage, instead of just open/close which i do now by just running open/close for 3 secs :) Would be nice to show the calibration and percentage on the screen.

Will let you know if i get any further!

**Comment by mieg** [comment]
BTW I use esphome now, very simple one-way with the following yaml code:

switch:
  - platform: uart
    name: "eqiva3_open"
    data: 'b30\r\n'

  - platform: uart
    name: "eqiva3_close"
    data: 'f30\r\n'

**Comment by Jakeler** [comment]
Got a response and he published the code now:
https://github.com/UltraFX/eq3-thermostat-alt-fw
Have fun :D

**Comment by mieg** [comment]
great, thanks!
